return mv cmd to build and test before doing mv
OpenLiberty/application-stack pull request #67
Opened 2020-09-30 13:49 UTC by ajm01

2020-09-30 15:39 UTC, scottkurz commented on dev/devfile.yaml
> +                                                            && mvn -Dmaven.repo.local=/mvn/repository package
Small detail but maybe make the if/then indenting a bit more consistent:

```
      commandLine: if [ -e /projects/.disable-bld-cmd ]; then
                       echo "found the disable file" && echo "devBuild command will not run" && exit 0;
                   else
                       echo "will run the devBuild command" && mkdir -p /projects/target/liberty 
                                                            && if [ ! -d /projects/target/liberty/wlp ]; then 
                                                                   echo "...moving liberty"; mv /opt/ol/wlp /projects/target/liberty; 
                                                               fi
                                                            && mvn -Dmaven.repo.local=/mvn/repository package
                                                            && touch ./.disable-bld-cmd;
                   fi
```

2020-09-30 15:39 UTC, scottkurz commented on dev/devfile.yaml
>  commands:
Don't forget to bump up stack version.

2020-09-30 15:40 UTC, scottkurz requested changes
Small comments

2020-10-01 15:46 UTC, ajm01 commented on dev/devfile.yaml
>  commands:
bumped the version number

2020-10-01 16:58 UTC, scottkurz commented on dev/devfile.yaml
>        commandLine: if [ -e /projects/.disable-bld-cmd ];
include in alignment.

2020-10-01 16:58 UTC, scottkurz commented on dev/devfile.yaml
> +                                                                 then echo "STACK WARNING - LIBERTY RUNTIME WAS LOADED FROM HOST";
Warning msg would be confusing if we did a 2nd package after the 1st failed (but the mv had already been done).

2020-10-01 19:18 UTC, scottkurz commented on dev/devfile.yaml
> +                                                                 then echo "STACK WARNING - LIBERTY RUNTIME WAS LOADED FROM HOST";
nm..you handled this..sorry

2020-10-01 19:18 UTC, scottkurz approved these changes
LGTM

2020-10-01 20:52 UTC, merged